### ISSUE TITLE
Repositórios

### ISSUE THREAD

**Issue by rodrigondec** [daal-imd/integraTI-Web#1]
@gellyviana percebi agora que foi criado só o repositório `discentes-bti`. Mas acho que será preciso um repo pra api e outro pro front. Sugiro criar com o nome `discentes-bti-api`ou `discentes-btiAPI` ou apenas `discentes-api`

**Comment by gellyviana** [comment]
Ok, vou criar os dois repositórios

**Comment by daal-imd** [comment]
eu criei dois repositórios (integraTI-Web e integraTI-Api). Veja se está certo!

**Comment by rodrigondec** [comment]
Estão, só falta o acesso para o meu user no integraTI-Api

**Comment by daal-imd** [comment]
@rodrigondec devidamente adicionado ;)
